set serveroutput on
alter session set nls_date_format='yyyy-mm-dd hh24:mi';
begin
for x in (select * from v$database) loop
dbms_output.put_line('=============================================');
dbms_output.put_line('DBID                          : '||x.DBID);
dbms_output.put_line('NAME                          : '||x.NAME);
dbms_output.put_line('CREATED                       : '||x.CREATED);
dbms_output.put_line('RESETLOGS_CHANGE#             : '||x.RESETLOGS_CHANGE#);
dbms_output.put_line('RESETLOGS_TIME                : '||x.RESETLOGS_TIME);
dbms_output.put_line('PRIOR_RESETLOGS_CHANGE#       : '||x.PRIOR_RESETLOGS_CHANGE#);
dbms_output.put_line('PRIOR_RESETLOGS_TIME          : '||x.PRIOR_RESETLOGS_TIME);
dbms_output.put_line('LOG_MODE                      : '||x.LOG_MODE);
dbms_output.put_line('CHECKPOINT_CHANGE#            : '||x.CHECKPOINT_CHANGE#);
dbms_output.put_line('ARCHIVE_CHANGE#               : '||x.ARCHIVE_CHANGE#);
dbms_output.put_line('CONTROLFILE_TYPE              : '||x.CONTROLFILE_TYPE);
dbms_output.put_line('CONTROLFILE_CREATED           : '||x.CONTROLFILE_CREATED);
dbms_output.put_line('CONTROLFILE_SEQUENCE#         : '||x.CONTROLFILE_SEQUENCE#);
dbms_output.put_line('CONTROLFILE_CHANGE#           : '||x.CONTROLFILE_CHANGE#);
dbms_output.put_line('CONTROLFILE_TIME              : '||x.CONTROLFILE_TIME);
dbms_output.put_line('OPEN_RESETLOGS                : '||x.OPEN_RESETLOGS);
dbms_output.put_line('VERSION_TIME                  : '||x.VERSION_TIME);
dbms_output.put_line('OPEN_MODE                     : '||x.OPEN_MODE);
dbms_output.put_line('PROTECTION_MODE               : '||x.PROTECTION_MODE);
dbms_output.put_line('PROTECTION_LEVEL              : '||x.PROTECTION_LEVEL);
dbms_output.put_line('REMOTE_ARCHIVE                : '||x.REMOTE_ARCHIVE);
dbms_output.put_line('ACTIVATION#                   : '||x.ACTIVATION#);
dbms_output.put_line('SWITCHOVER#                   : '||x.SWITCHOVER#);
dbms_output.put_line('DATABASE_ROLE                 : '||x.DATABASE_ROLE);
dbms_output.put_line('ARCHIVELOG_CHANGE#            : '||x.ARCHIVELOG_CHANGE#);
dbms_output.put_line('ARCHIVELOG_COMPRESSION        : '||x.ARCHIVELOG_COMPRESSION);
dbms_output.put_line('SWITCHOVER_STATUS             : '||x.SWITCHOVER_STATUS);
dbms_output.put_line('DATAGUARD_BROKER              : '||x.DATAGUARD_BROKER);
dbms_output.put_line('GUARD_STATUS                  : '||x.GUARD_STATUS);
dbms_output.put_line('SUPPLEMENTAL_LOG_DATA_MIN     : '||x.SUPPLEMENTAL_LOG_DATA_MIN);
dbms_output.put_line('SUPPLEMENTAL_LOG_DATA_PK      : '||x.SUPPLEMENTAL_LOG_DATA_PK);
dbms_output.put_line('SUPPLEMENTAL_LOG_DATA_UI      : '||x.SUPPLEMENTAL_LOG_DATA_UI);
dbms_output.put_line('FORCE_LOGGING                 : '||x.FORCE_LOGGING);
dbms_output.put_line('PLATFORM_ID                   : '||x.PLATFORM_ID);
dbms_output.put_line('PLATFORM_NAME                 : '||x.PLATFORM_NAME);
dbms_output.put_line('RECOVERY_TARGET_INCARNATION#  : '||x.RECOVERY_TARGET_INCARNATION#);
dbms_output.put_line('LAST_OPEN_INCARNATION#        : '||x.LAST_OPEN_INCARNATION#);
dbms_output.put_line('CURRENT_SCN                   : '||x.CURRENT_SCN);
dbms_output.put_line('FLASHBACK_ON                  : '||x.FLASHBACK_ON);
dbms_output.put_line('SUPPLEMENTAL_LOG_DATA_FK      : '||x.SUPPLEMENTAL_LOG_DATA_FK);
dbms_output.put_line('SUPPLEMENTAL_LOG_DATA_ALL     : '||x.SUPPLEMENTAL_LOG_DATA_ALL);
dbms_output.put_line('DB_UNIQUE_NAME                : '||x.DB_UNIQUE_NAME);
dbms_output.put_line('STANDBY_BECAME_PRIMARY_SCN    : '||x.STANDBY_BECAME_PRIMARY_SCN);
dbms_output.put_line('FS_FAILOVER_STATUS            : '||x.FS_FAILOVER_STATUS);
dbms_output.put_line('FS_FAILOVER_CURRENT_TARGET    : '||x.FS_FAILOVER_CURRENT_TARGET);
dbms_output.put_line('FS_FAILOVER_THRESHOLD         : '||x.FS_FAILOVER_THRESHOLD);
dbms_output.put_line('FS_FAILOVER_OBSERVER_PRESENT  : '||x.FS_FAILOVER_OBSERVER_PRESENT);
dbms_output.put_line('FS_FAILOVER_OBSERVER_HOST     : '||x.FS_FAILOVER_OBSERVER_HOST);
dbms_output.put_line('CONTROLFILE_CONVERTED         : '||x.CONTROLFILE_CONVERTED);
dbms_output.put_line('PRIMARY_DB_UNIQUE_NAME        : '||x.PRIMARY_DB_UNIQUE_NAME);
dbms_output.put_line('SUPPLEMENTAL_LOG_DATA_PL      : '||x.SUPPLEMENTAL_LOG_DATA_PL);
dbms_output.put_line('MIN_REQUIRED_CAPTURE_CHANGE#  : '||x.MIN_REQUIRED_CAPTURE_CHANGE#);
end loop;
end;
/
